### ISSUE TITLE
Design 'Kute app' logo

### ISSUE THREAD

**Issue by charithccmc** [scorelab/kute#1]
Design 'Kute app' logo

**Comment by icancode23** [comment]
@Dilu9218 mam has anyone started working on this or can i start doing something on it..?

**Comment by Dilu9218** [comment]
@icancode23  yes you can work on this to show your contribution. But remember this is not a GSoC task. You can work on more features that require coding to get familiar with the app which I think would help prepare a good proposal for GSoC.

**Comment by vihanga-liyanage** [comment]
Being dealt with via GCI 2017.
