### ISSUE TITLE
string.xml does not have the facebook and google api  keys 

### ISSUE THREAD

**Issue by icancode23** [scorelab/kute#24]
There are no strings facebook_app_id and googleMapsApi in the values folder as a result of which the gradle does not build

**Comment by icancode23** [comment]
#25

**Comment by NickHub4017** [comment]
yes we removed them. Because we use our own account to develop the application. 
So what you can do is use your own private account - But don't add it to any of the commits. 
Also You have to use google-services.json file.

**Comment by icancode23** [comment]
@NickHub4017 sir do i have to generate my own google services file

**Comment by Dilu9218** [comment]
@icancode23  yes you have to. And then copy it to the app directory.

**Comment by icancode23** [comment]
@Dilu9218 and i dont have to push it as a part of the commit i guess thats obvious right..?

**Comment by icancode23** [comment]
@Dilu9218 mam can you also tell me a platform where i can communicate more doubts about some functionality as on the gitter group i could not find you or @NickHub4017  sir.....
